### ISSUE TITLE
New release on rubygems

### ISSUE THREAD

**Issue by hellvinz** [madrobby/zaru#18]
Hi! Now that the new code and tests have been merged, would it be possible to
- remove the circle.ci configuration entirely to get green builds?
![image](https://user-images.githubusercontent.com/8229/229799006-93cace03-c4d3-4116-bcdc-24f2aa8f715d.png)
- Do a rubygems release?
Best.

**Comment by madrobby** [comment]
I've removed the CircleCI config and renamed the default branch to `main`. A new rubygems release is incoming.
