### ISSUE TITLE
White space doesn't collapse

### ISSUE THREAD

**Issue by nickiii** [madrobby/zaru#6]
Hello,

Today I was working on a ruby script and I realized that zaru don't collapse the white space if the white spaces are around a filtered letter (like "me | you").
This was causing me a problem when I was using sanitize twice.

Thanks.

**Comment by madrobby** [comment]
Thanks for reporting! I shall get that fixed :)

**Comment by madrobby** [comment]
Thanks again—I've pushed up version 0.2.0 which fixes this issue.
